[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=root:sail

[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:php]
command=%(ENV_SUPERVISOR_PHP_COMMAND)s
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:reverb]
command=php /var/www/html/artisan reverb:start
user=sail
autostart=true
autorestart=true

[program:queue-worker]
command=php /var/www/html/artisan queue:work
user=sail
autostart=true
autorestart=true

[program:cron]
command=/usr/sbin/cron -f
user=root
autostart=true
autorestart=true
